### ISSUE TITLE
AWarn2 Lua Error

### ISSUE THREAD

**Issue by AuroraEN** [meepdarknessmeep/gmodutil#1]
`net.Start("AWarnChatMessage") net.WriteTable({ Color(60,60,60), "[", Color(30,90,150), "AWarn", Color(60,60,60), "] ", Color(255,255,255), "Value ", Color(0,0,0), "(" .. key .. ") ", Color(255,255,255), "has been set to ", Color(0,0,0), "(" .. val .. ")" }) net.Broadcast()` 
where key is a string and var is an integer. They are not nil.

gives off the following error:
```
[ERROR] addons/gmodutil-master/lua/gmodutil/sh_nettables.lua:468: bad argument #1 to 'WriteUInt' (number expected, got nil)
  1. WriteUInt - [C]:-1
   2. unknown - addons/gmodutil-master/lua/gmodutil/sh_nettables.lua:468
    3. WriteTable - addons/gmodutil-master/lua/gmodutil/sh_nettables.lua:596
     4. awarn_saveservervalue - addons/awarn2/lua/awarn/modules/awarn_sqlite.lua:82
      5. func - addons/awarn2/lua/autorun/server/sv_awarn.lua:220
       6. unknown - lua/includes/modules/net.lua:32
```

It functions properly without gmodutil.

**Comment by meepdarknessmeep** [comment]
Seems like I accidentally forgot that 0 is a terminator, is it fixed?

**Comment by AuroraEN** [comment]
Yes, it is working properly now.
Thanks for your work!
